server:
  port: 8080

spring:
  h2:
    console:
      enabled:
        true
      path: /h2-console
  security:
    user:
      name: admin
      password: admin00!
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/task
    username: sa
    password: 